# -*- coding: utf-8 -*-
"""Supervised Machine Learning Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NwhsDvZhMMHDPVJgnTJCIVEG7lPdMcBC

# Prediction Using Supervised **Learning**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Data Import """

dataset = pd.read_csv("STScores.csv")
dataset

dataset.shape # it will print the row and coloumn count.
dataset.size # it will print the size of the dataset for all.

dataset.head(2) # it will print head or top rows values form the data..

dataset.tail(2) # it will print bottom values of the dataset....

dataset.columns
dataset.info()

dataset.describe()

dataset.iloc[:7,:6] # in this slicing before comma we call the rows and in second side we called column for the same...

"""# **Data Visualization By Using Scator Plot..**"""

x=dataset["Hours"]
y=dataset["Scores"]
plt.scatter(x,y,color='b')
plt.xlabel("Hours")
plt.ylabel("Scores")
plt.title("dataset")
plt.show()

"""# **Divide the dataset into traning and testing dataset..**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x=dataset.iloc[:,:-1].values # it is input data, which means that we will give the hours as input and predict the scores.
y=dataset.iloc[:,1].values
print(x)
print(y)

import sklearn
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=1/4,random_state=1)

"""# **Creating a Simple Linear Model.**"""

from sklearn.linear_model import LinearRegression
model = LinearRegression() #y=ax+b

model.fit(xtrain,ytrain)

"""# **Predictions**"""

y_pred = model.predict(xtest)
y_pred

ytest

model.predict([[9.25]]) #It is a prediction for 9.25 hours learning and got 93.82 score..

model.coef_

model.intercept_

plt.scatter(xtrain,ytrain,color='black')
plt.plot(xtrain,model.predict(xtrain),color='red')
plt.xlabel('Hours')
plt.ylabel('Scores')
plt.show()